@startuml Pyshical Architecture

node "Personal Device" {
    [ItemSwap(Flutter)]
}

node "Firebase" {
        [Authentication]
        database "Firestore Database"
        database "Realtime Database"
        [Messaging]
}

[ItemSwap(Flutter)] ..> [Authentication]
[ItemSwap(Flutter)] ..> [Messaging]
[ItemSwap(Flutter)] ..> "Firestore Database"
[ItemSwap(Flutter)] ..> "Realtime Database"

"Personal Device" "many" --> "1" "Firebase"

@enduml