// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIKNEoOG9LqxdEJO1N0Fui-aNjB3MCdI',
    appId: '1:383064151378:web:09054ece68c07473e3168b',
    messagingSenderId: '383064151378',
    projectId: 'itemswap-5af05',
    authDomain: 'itemswap-5af05.firebaseapp.com',
    databaseURL: 'https://itemswap-5af05-default-rtdb.firebaseio.com',
    storageBucket: 'itemswap-5af05.firebasestorage.app',
    measurementId: 'G-QSR58843VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfamuQU55j3AppIyvVYkFC_2ZMhTcWrVQ',
    appId: '1:383064151378:android:d9f34b4168b679dbe3168b',
    messagingSenderId: '383064151378',
    projectId: 'itemswap-5af05',
    databaseURL: 'https://itemswap-5af05-default-rtdb.firebaseio.com',
    storageBucket: 'itemswap-5af05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd6MjLu-f7gAjTSV3AMjiXmvIc8KKYcng',
    appId: '1:383064151378:ios:787e6d8f5cd56e80e3168b',
    messagingSenderId: '383064151378',
    projectId: 'itemswap-5af05',
    databaseURL: 'https://itemswap-5af05-default-rtdb.firebaseio.com',
    storageBucket: 'itemswap-5af05.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd6MjLu-f7gAjTSV3AMjiXmvIc8KKYcng',
    appId: '1:383064151378:ios:787e6d8f5cd56e80e3168b',
    messagingSenderId: '383064151378',
    projectId: 'itemswap-5af05',
    databaseURL: 'https://itemswap-5af05-default-rtdb.firebaseio.com',
    storageBucket: 'itemswap-5af05.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNIKNEoOG9LqxdEJO1N0Fui-aNjB3MCdI',
    appId: '1:383064151378:web:15750f958cf8256ce3168b',
    messagingSenderId: '383064151378',
    projectId: 'itemswap-5af05',
    authDomain: 'itemswap-5af05.firebaseapp.com',
    databaseURL: 'https://itemswap-5af05-default-rtdb.firebaseio.com',
    storageBucket: 'itemswap-5af05.firebasestorage.app',
    measurementId: 'G-VFGTWJTSL1',
  );

}